Fix typescript errors
Remove rootDir from example/tsconfig.json

Inclusion was causing TS6059 'rootDir' is expected
to contain all source files error. Suggestion to remove from:
https://github.com/wmonk/create-react-app-typescript/pull/74

Change tsconfig.json compiler target to es7
With target set to es6, was receiving error:
ERROR in /home/jthetzel/src/react-mapbox-gl/src/layer.ts
(206,22): error TS2339: Property 'includes' does not exist on type 'number[]'.
Suggestion to try es7:
https://github.com/AngularClass/angular-starter/issues/931#issuecomment-244001423

Removing carets from devDependencies
Presume this is preferred, as master branch does not
use carets.